  <?php  
  Echo ' <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">  '; 
  Echo ' <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">  '; 
  Echo ' <html>  '; 
  Echo '     <head>  '; 
  Echo '         <title>Obaid Habib</title>  '; 
  Echo '           '; 
  Echo ' 		<link rel="stylesheet" href="css/mainmenuestylesheet.css" />  '; 
  Echo ' 		<link rel="stylesheet" href="css/footercss.css" />  '; 
  Echo ' 		<link rel="stylesheet" href="css/headercss.css" />  '; 
  Echo ' 		<link rel="stylesheet" href="css/stylesocialnetworks.css" />  '; 
  Echo ' 		<link rel="stylesheet" href="css/myinfohomecss.css" />  '; 
  Echo '         <link rel="stylesheet" href="css/style.css" type="text/css" media="screen"/>  '; 
  Echo ' 		<link rel="stylesheet" href="css/slider1.css" type="text/css" media="screen"/>  '; 
  Echo ' 		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>  '; 
  Echo ' 	     <script type="text/javascript" src="jquery/script.js"></script>  '; 
  Echo '   '; 
  Echo ' 		<style>  '; 
  Echo ' 		body {   '; 
  Echo ' 			  '; 
  Echo ' 			background:#000 no-repeat center center fixed ;   '; 
  Echo ' 			-webkit-background-size: cover;  '; 
  Echo ' 			-moz-background-size: cover;  '; 
  Echo ' 			-o-background-size: cover;  '; 
  Echo ' 			background-size:cover;  '; 
  Echo ' 			  '; 
  Echo ' 			}  '; 
  Echo ' 			 #page-wrap1{ width: 100%; margin: -5px auto; padding: 20px;  -moz-box-shadow: 0 0 20px black; -webkit-box-shadow: 0 0 20px black; box-shadow: 0 0 40px black; }  '; 
  Echo ' 		#div1{  '; 
  Echo ' 		width:680px;  '; 
  Echo ' 		height:200px;  '; 
  Echo ' 		margin-top:-810px;  '; 
  Echo ' 		margin-left:210px;  '; 
  Echo ' 		background : white;  '; 
  Echo ' 		}  '; 
  Echo ' 		  '; 
  Echo ' 		#div2{  '; 
  Echo ' 		width:680px;  '; 
  Echo ' 		height:200px;  '; 
  Echo ' 		  '; 
  Echo ' 		margin-top:-200px;  '; 
  Echo ' 		margin-left:210px;  '; 
  Echo ' 		background : white;  '; 
  Echo ' 		}  '; 
  Echo ' 		#div3{  '; 
  Echo ' 		width:680px;  '; 
  Echo ' 		height:200px;  '; 
  Echo ' 		  '; 
  Echo ' 		margin-top:-200px;  '; 
  Echo ' 		margin-left:210px;  '; 
  Echo ' 		background : white;  '; 
  Echo ' 		}  '; 
  Echo ' 				.slider1{  '; 
  Echo ' width:330px;  '; 
  Echo ' height:200px;  '; 
  Echo ' overflow:hidden;  '; 
  Echo '   '; 
  Echo ' margin-left:-40px;  '; 
  Echo ' margin-top:210px;  '; 
  Echo '   '; 
  Echo '   '; 
  Echo '   '; 
  Echo '   '; 
  Echo ' }  '; 
  Echo ' .slider1 img li {  '; 
  Echo ' width:300px;  '; 
  Echo ' height:200px;  '; 
  Echo ' display:none;  '; 
  Echo ' }  '; 
  Echo ' h3 .post {  '; 
  Echo '    '; 
  Echo '     border-bottom: 1px solid black;   '; 
  Echo ' }  '; 
  Echo ' #infot{  '; 
  Echo ' margin-left:300px;  '; 
  Echo ' font-size:20px;  '; 
  Echo '   '; 
  Echo ' }	  '; 
  Echo ' #test{  '; 
  Echo '    '; 
  Echo ' margin-top:-200px;  '; 
  Echo ' margin-left:340px;  '; 
  Echo ' }	  '; 
  Echo '   '; 
  Echo ' 		</style>  '; 
  Echo ' 	  '; 
  Echo '          '; 
  Echo '     </head>  '; 
  Echo '   '; 
  Echo '     <body>  '; 
  Echo ' 	  '; 
  Echo ' 	  '; 
  Echo ' 		<div id = "mainpage"class="content">  '; 
  Echo ' 			  '; 
  Echo ' 			  '; 
  Echo ' 			<ul id="sdt_menu" class="sdt_menu">  '; 
  Echo ' 				<li>  '; 
  Echo ' 					<a href="index.html">  '; 
  Echo ' 						<img src="Navigationimages/1.jpg" alt=""/>  '; 
  Echo ' 						<span class="sdt_active"></span>  '; 
  Echo ' 						<span class="sdt_wrap">  '; 
  Echo ' 							<span class="sdt_link">Home</span>  '; 
  Echo ' 							<span class="sdt_descr">Where ideas get born</span>  '; 
  Echo ' 						</span>  '; 
  Echo ' 					</a>  '; 
  Echo ' 				</li>  '; 
  Echo ' 				<li>  '; 
  Echo ' 					<a href="#">  '; 
  Echo ' 						<img src="Navigationimages/2.jpg"alt=""/>  '; 
  Echo ' 						<span class="sdt_active"></span>  '; 
  Echo ' 						<span class="sdt_wrap">  '; 
  Echo ' 							<span class="sdt_link">Portfolio</span>  '; 
  Echo ' 							<span class="sdt_descr">Me And My work</span>  '; 
  Echo ' 						</span>  '; 
  Echo ' 					</a>  '; 
  Echo ' 					<div class="sdt_box">  '; 
  Echo ' 							<a href="portofolio/whoIam.html">Who I Am</a>  '; 
  Echo ' 							<a href="portofolio/Skills/skills.html">Skills</a>  '; 
  Echo ' 							<a href="#">Photography</a>  '; 
  Echo ' 					</div>  '; 
  Echo ' 				</li>  '; 
  Echo ' 				  '; 
  Echo ' 				<li>  '; 
  Echo ' 					<a href="#">  '; 
  Echo ' 						<img src="Navigationimages/3.gif" alt=""/>  '; 
  Echo ' 						<span class="sdt_active"></span>  '; 
  Echo ' 						<span class="sdt_wrap">  '; 
  Echo ' 							<span class="sdt_link">Kashmir</span>  '; 
  Echo ' 							<span class="sdt_descr">My Country</span>  '; 
  Echo ' 						</span>  '; 
  Echo ' 					</a>  '; 
  Echo ' 					<div class="sdt_box">  '; 
  Echo ' 							<a href="Kashmir/History/history.html">History</a>  '; 
  Echo ' 							<a href="Kashmir/tourism/tourism.html">Tourism</a>  '; 
  Echo ' 							<a href="#">Photography</a>  '; 
  Echo ' 					</div>  '; 
  Echo ' 				</li>  '; 
  Echo ' 				  '; 
  Echo ' 				<li>  '; 
  Echo ' 					<a href="#">  '; 
  Echo ' 						<img src="Navigationimages/4.jpg" alt=""/>  '; 
  Echo ' 						<span class="sdt_active"></span>  '; 
  Echo ' 						<span class="sdt_wrap">  '; 
  Echo ' 							<span class="sdt_link">New Technologies</span>  '; 
  Echo ' 							<span class="sdt_descr">Explore what \'s new</span>  '; 
  Echo ' 						</span>  '; 
  Echo ' 					</a>  '; 
  Echo ' 					<div class="sdt_box">  '; 
  Echo ' 						<a href="NewTechnologies/computers/computers.html">computers</a>  '; 
  Echo ' 						<a href="NewTechnologies/mobiles/mobiles.html">Mobiles</a>  '; 
  Echo ' 						  '; 
  Echo ' 					</div>  '; 
  Echo ' 				</li>  '; 
  Echo ' 				<li>  '; 
  Echo ' 					<a href="contact/contact.html">  '; 
  Echo ' 						<img src="Navigationimages/5.jpg" alt=""/>  '; 
  Echo ' 						<span class="sdt_active"></span>  '; 
  Echo ' 						<span class="sdt_wrap">  '; 
  Echo ' 							<span class="sdt_link">Contact</span>  '; 
  Echo ' 							<span class="sdt_descr">How to reach me</span>  '; 
  Echo ' 						</span>  '; 
  Echo ' 					</a>  '; 
  Echo ' 				</li>  '; 
  Echo ' 			</ul>  '; 
  Echo ' 		</div  '; 
  Echo ' 		  '; 
  Echo ' 		  '; 
  Echo '        <!--slider -->  '; 
  Echo ' 	     '; 
  Echo ' 	   <div class="slider">  '; 
  Echo '       <ul class="slides">  '; 
  Echo '         <li><img src="hompagesliderimages/13.jpg" /></li>  '; 
  Echo ' 		<li><img src="hompagesliderimages/1.jpg" /></li>  '; 
  Echo ' 		<li><img src="hompagesliderimages/2.jpg" /></li>  '; 
  Echo ' 		<li><img src="hompagesliderimages/2h.jpg" /></li>  '; 
  Echo ' 		<li><img src="hompagesliderimages/3.jpg" /></li>  '; 
  Echo ' 		<li><img src="hompagesliderimages/5.jpg" /></li>  '; 
  Echo ' 		<li><img src="hompagesliderimages/6.jpg" /></li>  '; 
  Echo ' 		<li><img src="hompagesliderimages/7.jpg" /></li>  '; 
  Echo ' 		<li><img src="hompagesliderimages/8.jpg" /></li>  '; 
  Echo ' 		<li><img src="hompagesliderimages/14.jpg" /></li>  '; 
  Echo '           '; 
  Echo '           '; 
  Echo '       </ul>  '; 
  Echo ' 	    '; 
  Echo '       </div>  '; 
  Echo ' 	    '; 
  Echo ' 	<div id = "header">  '; 
  Echo ' 	<h1 id = "heading">Obaid Habib</h1>  '; 
  Echo ' 	  '; 
  Echo ' 	</div>  '; 
  Echo ' 	<div class ="footerclass" id = "footer">  '; 
  Echo ' 	<h1 id = "footertext">DEVELOPED BY : OBAID HABIB </h1>  '; 
  Echo ' 	  '; 
  Echo ' 	</div>  '; 
  Echo ' 	  '; 
  Echo '        <!--slider -->  '; 
  Echo ' 	   <div id = "imageandinfoonhome">  '; 
  Echo ' 	   <img src="myimages/images.png"  width="250"  '; 
  Echo '         height="250" />  '; 
  Echo '         <p id ="deschome">Hi..! This is me Obaid Habib .This is my personal web site where you can find information about me and my country <b>Kashmir </b>  '; 
  Echo ' 		 .In addition to my portfolio you\'ll find some more information about new technologies and mobile phone development like<em>  Android </em> and<em> Ios</em> development   '; 
  Echo '          and new releases .		   '; 
  Echo ' 		  '; 
  Echo ' 		</p>  '; 
  Echo ' 	   </div>  '; 
  Echo ' 	     '; 
  Echo ' 	  <div id = "div1">  '; 
  Echo ' 	  <a href = "Kashmir/tourism/tourism.html">  '; 
  Echo ' 	  <div class="slider1">  '; 
  Echo '       <ul class="slides">  '; 
  Echo '           '; 
  Echo '         <li><img src="11.jpg" /></li>  '; 
  Echo ' 		 <li><img src="10j.jpg" /></li>  '; 
  Echo '           '; 
  Echo '       </ul>  '; 
  Echo ' 	    '; 
  Echo '       </div>  '; 
  Echo ' 	  </a>  '; 
  Echo ' 	  <h1 id = "test">Tourism in kashmir</h1>  '; 
  Echo ' 	  <p id = "infot">Jammu and Kashmir, over the years, has been regarded as one of the major tourist hot   '; 
  Echo ' 			         spotsin Asia. Owing to the cool and pleasant climate and its scenic landscapes  '; 
  Echo ' 			         Jammu and Kashmir showcases itself as a valley right out of heaven<a href ="Kashmir/tourism/tourism.html">Read more...</a></p>  '; 
  Echo ' 	  </div>  '; 
  Echo ' 	  <div id = "div2">  '; 
  Echo ' 	  <a href = "NewTechnologies/mobiles/JOLLA.html">  '; 
  Echo ' 	  <div class="slider1">  '; 
  Echo '        <ul class="slides">  '; 
  Echo '         <li><img src="10.jpg" /></li>  '; 
  Echo ' 		 <li><img src="9.jpg" /></li>  '; 
  Echo ' 		  <li><img src="4.jpg" /></li>  '; 
  Echo ' 		    '; 
  Echo '       </ul>  '; 
  Echo ' 	    '; 
  Echo '       </div>  '; 
  Echo ' 	  </a>  '; 
  Echo ' 	  <h1 id = "test">JOLLA BOASTS ITS SAILFISH OS WILL RUN ANDROID APPS</h1>  '; 
  Echo ' 	  <p id = "infot">Jolla has announced its Sailfish operating system is compatible with both the Android <a href ="NewTechnologies/mobiles/JOLLA.html">Read more...</a></p>  '; 
  Echo ' 	    '; 
  Echo ' 	  </div>  '; 
  Echo ' 	    '; 
  Echo ' 	   <div id = "div3">  '; 
  Echo ' 	   <a href = "NewTechnologies/computers/notouching.html">  '; 
  Echo ' 	   <div class="slider1">  '; 
  Echo '        <ul class="slides">  '; 
  Echo '          <li><img src="2.jpg" /></li>  '; 
  Echo '         <li><img src="1.jpg" /></li>  '; 
  Echo '         <li><img src="7.jpg" /></li>  '; 
  Echo '      '; 
  Echo '           '; 
  Echo '       </ul>  '; 
  Echo ' 	    '; 
  Echo '       </div>  '; 
  Echo ' 	  </a>  '; 
  Echo ' 	  <h1 id = "test">NO TOUCHING! WE GO HANDS-OFF  HP ENVY 17 </h1>  '; 
  Echo ' 	  <p id = "infot">It is been less than a decade since consumers started getting used to  <a href ="NewTechnologies/computers/notouching.html">Read more...</a></p>  '; 
  Echo ' 	  </div>  '; 
  Echo ' 	  </div>  '; 
  Echo ' 	   <!--slider -->  '; 
  Echo ' 	    '; 
  Echo '         <!-- The JavaScript -->  '; 
  Echo ' 	       '; 
  Echo '         <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>  '; 
  Echo ' 		<script type="text/javascript" src="jquery/jquery.easing.1.3.js"></script>  '; 
  Echo '         <script type="text/javascript" src = "jquery/menuejava.js"></script>  '; 
  Echo '   '; 
  Echo '         <script src="jquery/jquery.blueberry.js"></script>  '; 
  Echo ' 		<script src="jquery/jquerysliderrun.js"></script>  '; 
  Echo ' 		     '; 
  Echo ' 	   '; 
  Echo ' 	  <script src="jquery/jquerysliderrun2.js"></script>  '; 
  Echo ' 		  '; 
  Echo '           '; 
  Echo ' 		   '; 
  Echo '           '; 
  Echo '   '; 
  Echo '   '; 
  Echo ' 		  '; 
  Echo '              '; 
  Echo '           '; 
  Echo '     </body>  '; 
  Echo ' </html>  '; 
  ?> 
